"""
Cross-Document Verifier — enhanced with 6 new check categories,
statute-grounded RAG, composite risk scoring, self-critique pass,
few-shot retrieval from human feedback, and legal-opinion-format report.
"""

from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime

import httpx
from dotenv import load_dotenv
from groq import Groq

from backend.logger import get_logger
from backend.services.rate_limiter import groq_limiter, LLMCallTracker
from backend.services.risk_scorer import compute_risk_score
from backend.services.few_shot_retriever import retrieve_corrections, format_few_shot_examples

load_dotenv()

logger = get_logger(__name__)

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = "llama-3.3-70b-versatile"
FALLBACK_GROQ_MODEL = "llama-3.1-8b-instant"

# ── Statutory reference guide for expected document checklists ────────────

EXPECTED_DOCUMENTS_BY_PROPERTY_TYPE = {
    "apartment": [
        "SALE_DEED", "ENCUMBRANCE_CERTIFICATE", "PROPERTY_REGISTER_CARD",
        "KHATA", "PROPERTY_TAX_ASSESSMENT", "E_PAYMENT_RECEIPT",
        "OCCUPANCY_CERTIFICATE", "BUILDER_BUYER_AGREEMENT",
    ],
    "house": [
        "SALE_DEED", "ENCUMBRANCE_CERTIFICATE", "PROPERTY_REGISTER_CARD",
        "KHATA", "PROPERTY_TAX_ASSESSMENT", "E_PAYMENT_RECEIPT",
        "MUTATION",
    ],
    "land": [
        "SALE_DEED", "ENCUMBRANCE_CERTIFICATE", "PROPERTY_REGISTER_CARD",
        "KHATA", "RTC_PAHANI", "MUTATION", "CONVERSION_ORDER",
    ],
    "commercial": [
        "SALE_DEED", "ENCUMBRANCE_CERTIFICATE", "PROPERTY_REGISTER_CARD",
        "KHATA", "PROPERTY_TAX_ASSESSMENT", "E_PAYMENT_RECEIPT",
        "OCCUPANCY_CERTIFICATE",
    ],
}

CROSS_DOC_SYSTEM_PROMPT = """You are a SENIOR VERIFICATION OFFICER with 20 years of experience in Karnataka property law.
You are reviewing a complete property case bundle and must produce a professional verification report.

## YOUR TASK
Given the structured data from ALL documents in this case, along with PER-DOCUMENT verification notes already generated by the document structurer, you must:

1. **Cross-document checks** — identify issues that span multiple documents:
   - Full Title & Ownership Chain Tracing
   - Encumbrance / Pending Mortgages analysis
   - EC Transaction Gaps > 3 years
   - EC Search Coverage < 13 years
   - Survey Number / CTS Number consistency
   - Name transliteration variations (Kannada vs English)
   - Stamp duty consistency
   - Missing critical documents

2. **ADDITIONAL CHECKS — reason like a lawyer:**
   - Chain-of-title completeness over 30 years (Evidence Act Sec. 90)
   - Authority-to-sign verification (POA, Board Resolution, HUF/Trust deed)
   - Inheritance/succession gaps
   - Valuation consistency (consideration vs guidance value vs market value)
   - RERA applicability check
   - Document recency (EC, guidance value expiry)
   - Expected-but-missing documents given property type

3. **Review per-document findings** — evaluate verification_notes already generated:
   - Flag false positives
   - Confirm high-confidence issues
   - Add legal reasoning context

4. **Produce structured JSON output**

## OUTPUT FORMAT — Return ONLY valid JSON:
{
    "verdict": "PASS | FLAGGED | MANUAL_REVIEW",
    "risk_score": <float>,
    "findings": [
        {
            "type": "<finding type>",
            "severity": "critical | high | medium | low",
            "doc_ids": ["doc_type1", "doc_type2"],
            "summary": "Short summary",
            "legal_detail": "Legal reasoning with statute citations",
            "suggestion": "Actionable recommendation",
            "confidence": 0.95,
            "statute_reference": "Section X of Act Y",
            "source_document_ref": "Specific field from source doc"
        }
    ],
    "final_report": "Structured legal opinion in the format below"
}

## FINAL REPORT STRUCTURE — Write the final_report as a structured legal opinion:

EXECUTIVE SUMMARY
[2-3 sentence overview]

VERDICT & RISK SCORE
Verdict: [PASS/FLAGGED/MANUAL_REVIEW]
Risk Score: [0-XX]
Risk Level: [Low/Moderate/High/Very High]

CRITICAL ISSUES (High Severity)
[For each critical finding, provide: statute citation, source document reference, explanation]

OTHER FINDINGS
[Medium and low severity findings grouped by category]

MISSING DOCUMENTS
[Documents that are expected but absent from the bundle]

RECOMMENDED NEXT STEPS
[Actionable items ordered by priority]

DISCLAIMER
This report is generated by an AI-assisted verification system and is not a substitute for an independent legal opinion from a qualified advocate. All findings should be independently verified by a human legal professional before any action is taken.
"""


def run_cross_doc_verification(documents: list[dict]) -> dict:
    """
    Run cross-document verification on all structured documents.
    Enhanced with statute RAG, few-shot retrieval, extended checks.
    """
    if not GROQ_API_KEY:
        return _fallback_verification(documents)

    # ── Retrieve few-shot corrections from human feedback ──────────────
    doc_types_in_bundle = {d.get("document_type") for d in documents if d.get("document_type")}
    few_shot_examples = ""
    for dt in doc_types_in_bundle:
        corrections = retrieve_corrections(dt)
        if corrections:
            few_shot_examples += format_few_shot_examples(corrections) + "\n"

    # ── Determine property type for expected-docs check ────────────────
    property_type = _detect_property_type(documents)

    # ── Run extended deterministic checks ──────────────────────────────
    deterministic_findings = []
    deterministic_findings.extend(_check_chain_of_title_years(documents))
    deterministic_findings.extend(_check_authority_to_sign(documents))
    deterministic_findings.extend(_check_inheritance_succession(documents))
    deterministic_findings.extend(_check_valuation_consistency(documents))
    deterministic_findings.extend(_check_rera_applicability(documents, property_type))
    deterministic_findings.extend(_check_document_recency(documents))
    deterministic_findings.extend(_check_expected_missing_docs(documents, property_type))

    _http_client = httpx.Client(timeout=httpx.Timeout(120.0, connect=30.0))
    client = Groq(api_key=GROQ_API_KEY, http_client=_http_client)

    doc_summaries = []
    for doc in documents:
        sd = doc.get("structured_json", {}) or {}
        vn = doc.get("verification_notes", []) or []
        summary = {
            "doc_id": doc.get("doc_id"),
            "document_type": doc.get("document_type"),
            "structured_fields": _compact_fields(sd),
            "per_doc_verification_notes": vn,
        }
        doc_summaries.append(summary)

    input_payload = {
        "total_documents": len(documents),
        "deterministic_findings": deterministic_findings,
        "documents": doc_summaries,
    }
    input_text = json.dumps(input_payload, indent=2, ensure_ascii=False)

    user_prompt = (
        "Review the following property case bundle and produce a verification report.\n\n"
        "NOTE: Deterministic checks have already been run. The findings are provided for context.\n"
        "Integrate them into your analysis but focus on cross-document reasoning.\n\n"
        f"{few_shot_examples}\n"
        f"CASE DOCUMENTS:\n{input_text}\n\n"
        "Return ONLY valid JSON matching the specified output format."
    )

    start = time.time()

    for model in [GROQ_MODEL, FALLBACK_GROQ_MODEL]:
        try:
            acquired = groq_limiter.wait_and_acquire()
            if not acquired:
                logger.warning("Rate limit wait timeout for cross-doc verifier")

            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": CROSS_DOC_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.1,
                max_tokens=8000,
                response_format={"type": "json_object"},
            )
            latency = int((time.time() - start) * 1000)
            raw = response.choices[0].message.content.strip()

            try:
                result = json.loads(raw)
            except json.JSONDecodeError:
                m = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', raw)
                if m:
                    result = json.loads(m.group(1))
                else:
                    raise

            usage = response.usage
            input_tokens = usage.prompt_tokens if usage else len(input_text) // 4
            output_tokens = usage.completion_tokens if usage else len(raw) // 4

            result.setdefault("verdict", "MANUAL_REVIEW")
            result.setdefault("findings", [])
            result.setdefault("final_report", raw if not result.get("final_report") else result["final_report"])

            # Merge deterministic findings with LLM findings
            llm_findings = result.get("findings", [])
            all_findings = deterministic_findings + llm_findings

            # Deduplicate by type + summary
            seen = set()
            unique_findings = []
            for f in all_findings:
                key = (f.get("type", ""), f.get("summary", "")[:100])
                if key not in seen:
                    seen.add(key)
                    unique_findings.append(f)
            all_findings = unique_findings

            # ── Compute composite risk score ────────────────────────────
            risk_result = compute_risk_score(all_findings)
            result["risk_score"] = risk_result["risk_score"]
            result["risk_score_details"] = risk_result
            result["findings"] = all_findings

            # Override verdict with risk-based verdict if more conservative
            if risk_result["verdict"] == "FLAGGED" and result.get("verdict") != "FLAGGED":
                result["verdict"] = "FLAGGED"
            elif risk_result["verdict"] == "MANUAL_REVIEW" and result.get("verdict") == "PASS":
                result["verdict"] = "MANUAL_REVIEW"

            # ── Ensure legal opinion format in final_report ─────────────
            result["final_report"] = _ensure_legal_opinion_format(
                result.get("final_report", ""), result["verdict"],
                risk_result, all_findings,
            )

            result["_analytics"] = {
                "model": model,
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "latency_ms": latency,
                "cost_usd": (input_tokens / 1_000_000 * 0.59) + (output_tokens / 1_000_000 * 0.79),
                "deterministic_findings_count": len(deterministic_findings),
            }

            LLMCallTracker.record(
                provider="groq", model=model, doc_type="cross_doc_verifier",
                input_tokens=input_tokens, output_tokens=output_tokens,
                cached_tokens=0, latency_ms=latency,
                cost_usd=result["_analytics"]["cost_usd"],
                retry_count=0, status="success",
            )

            return result

        except Exception as e:
            logger.error("Cross-doc verification with %s failed: %s", model, e)
            continue

    return _fallback_verification(documents, deterministic_findings)


# ── Extended deterministic check implementations ─────────────────────────


def _detect_property_type(documents: list[dict]) -> str:
    """Detect property type from structured data across docs."""
    for doc in documents:
        sd = doc.get("structured_json", {}) or {}
        # Check Sale Deed property_schedule
        ps = sd.get("property_schedule") or {}
        if ps.get("apartment_or_shop_number") or ps.get("project_name"):
            return "apartment"
        intended_usage = (ps.get("intended_usage") or "").lower()
        if "apartment" in intended_usage or "flat" in intended_usage:
            return "apartment"
        if "commercial" in intended_usage or "shop" in intended_usage:
            return "commercial"
        # Check Tax Assessment
        pd = sd.get("property_details") or {}
        ptype = (pd.get("property_type") or "").lower()
        if "apartment" in ptype or "flat" in ptype:
            return "apartment"
        if "commercial" in ptype:
            return "commercial"
        # Check PRC
        pi = sd.get("property_identification") or {}
        area = pi.get("area_sq_meters")
        if area and isinstance(area, (int, float)):
            if area > 1000:
                return "land"
    return "house"  # Default


def _check_chain_of_title_years(documents: list[dict]) -> list[dict]:
    """B2.1: Chain-of-title completeness over 30 years."""
    findings = []
    ec_docs = [d for d in documents if d.get("document_type") == "ENCUMBRANCE_CERTIFICATE"]
    for doc in ec_docs:
        sd = doc.get("structured_json", {}) or {}
        fm = sd.get("file_metadata") or {}
        start = fm.get("search_start_date")
        end = fm.get("search_end_date")
        if start and end:
            try:
                s = datetime.strptime(str(start)[:10], "%Y-%m-%d")
                e = datetime.strptime(str(end)[:10], "%Y-%m-%d")
                years = (e - s).days / 365.25
                if years < 13:
                    findings.append({
                        "type": "EC_GAP", "severity": "medium",
                        "doc_ids": ["ENCUMBRANCE_CERTIFICATE"],
                        "summary": f"EC search period covers only {years:.1f} years",
                        "legal_detail": f"EC search covers {years:.1f} years ({str(start)[:10]} to {str(end)[:10]}). "
                                        "Standard due diligence requires 13-30 years under Evidence Act Sec. 90.",
                        "suggestion": "Obtain additional ECs covering at least 13-30 years.",
                        "confidence": 1.0,
                        "statute_reference": "Indian Evidence Act, 1872 — Section 90",
                        "source_document_ref": f"search_start_date={start}, search_end_date={end}",
                    })
                    # Also flag if < 30 years as informational
                if years < 30:
                    coverage_note = {
                        "type": "EC_GAP", "severity": "low",
                        "doc_ids": ["ENCUMBRANCE_CERTIFICATE"],
                        "summary": f"Chain of title covers {years:.1f} years (benchmark: 30 years)",
                        "legal_detail": f"Total years covered: {years:.1f}. "
                                        "Evidence Act Sec. 90 recommends 30-year chain for marketable title. "
                                        "Consider older ECs for full coverage.",
                        "suggestion": "If title risk is high, obtain ECs covering full 30-year period.",
                        "confidence": 0.9,
                        "statute_reference": "Indian Evidence Act, 1872 — Section 90",
                        "source_document_ref": f"search_period_years={years:.1f}",
                    }
                    findings.append(coverage_note)

            except (ValueError, TypeError):
                pass

    # Calculate combined coverage from all documents
    all_dates = []
    for doc in documents:
        sd = doc.get("structured_json", {}) or {}
        fm = sd.get("file_metadata") or sd.get("document_metadata") or {}
        for date_field in ["execution_date", "registration_date", "date"]:
            val = fm.get(date_field)
            if val:
                try:
                    all_dates.append(datetime.strptime(str(val)[:10], "%Y-%m-%d"))
                except (ValueError, TypeError):
                    pass
        # EC ledger dates
        ledger = sd.get("historical_ledger") or sd.get("transactions") or []
        for tx in ledger:
            if isinstance(tx, dict):
                for date_field in ["execution_date", "registration_date"]:
                    val = tx.get(date_field)
                    if val:
                        try:
                            all_dates.append(datetime.strptime(str(val)[:10], "%Y-%m-%d"))
                        except (ValueError, TypeError):
                            pass

    if len(all_dates) >= 2:
        coverage_years = (max(all_dates) - min(all_dates)).days / 365.25
        if coverage_years < 13:
            findings.append({
                "type": "EC_GAP", "severity": "medium",
                "doc_ids": list({d.get("document_type") for d in documents if d.get("document_type")}),
                "summary": f"Combined document coverage: {coverage_years:.1f} years",
                "legal_detail": f"The combined set of documents spans only {coverage_years:.1f} years. "
                                "This is insufficient for a 13-30 year chain of title under Evidence Act Sec. 90.",
                "suggestion": "Collect older title deeds or ECs to establish a 30-year chain.",
                "confidence": 0.9,
                "statute_reference": "Indian Evidence Act, 1872 — Section 90",
                "source_document_ref": f"combined_coverage_years={coverage_years:.1f}",
            })

    return findings


def _check_authority_to_sign(documents: list[dict]) -> list[dict]:
    """B2.2: Authority-to-sign verification."""
    findings = []
    sale_deeds = [d for d in documents if d.get("document_type") == "SALE_DEED"]
    doc_types_present = {d.get("document_type") for d in documents if d.get("document_type")}

    for sd_doc in sale_deeds:
        sd = sd_doc.get("structured_json", {}) or {}
        parties = sd.get("parties") or {}
        vendors = parties.get("vendors") or []

        for vendor in vendors:
            name = (vendor.get("entity_name") or "").lower()
            represented_by = vendor.get("represented_by")
            # Check for corporate/HUF/trust indicators
            is_corporate = any(x in name for x in ["pvt ltd", "private limited", "limited", "ltd", "corp", "incorporated"])
            is_huf = "huf" in name or "hindu undivided family" in name
            is_trust = "trust" in name or "trustee" in name
            is_society = "society" in name or "association" in name or "co-operative" in name

            needs_authority = is_corporate or is_huf or is_trust or is_society

            if not needs_authority:
                continue

            has_poa = "POWER_OF_ATTORNEY" in doc_types_present or any(
                "poa" in (d.get("document_type") or "").lower() for d in documents
            )
            has_board_resolution = any(
                "board resolution" in (d.get("document_type") or "").lower()
                or "resolution" in (d.get("document_type") or "").lower()
                for d in documents
            )
            has_trust_deed = "TRUST_DEED" in doc_types_present

            if is_corporate and not has_board_resolution and not has_poa and not represented_by:
                findings.append({
                    "type": "UNVERIFIED_SIGNATORY_AUTHORITY", "severity": "high",
                    "doc_ids": ["SALE_DEED"],
                    "summary": f"Corporate seller '{vendor.get('entity_name')}' without supporting authority document",
                    "legal_detail": f"The seller '{vendor.get('entity_name')}' appears to be a corporate entity. "
                                    "No Board Resolution, Power of Attorney, or authorizing document found in the bundle. "
                                    "Under the Companies Act, 2013, a company can only execute deeds through authorized officers.",
                    "suggestion": "Obtain Board Resolution or Power of Attorney authorizing the signatory.",
                    "confidence": 0.85,
                    "statute_reference": "Companies Act, 2013 — Section 179",
                    "source_document_ref": f"vendor={vendor.get('entity_name')}",
                })

            if is_huf and represented_by is None:
                findings.append({
                    "type": "UNVERIFIED_SIGNATORY_AUTHORITY", "severity": "medium",
                    "doc_ids": ["SALE_DEED"],
                    "summary": f"HUF seller '{vendor.get('entity_name')}' — verify Karta authority",
                    "legal_detail": "An HUF can only act through its Karta (manager). "
                                    "If the represented_by field is empty, the Karta's authority to sell should be verified.",
                    "suggestion": "Confirm that the signatory is the Karta of the HUF.",
                    "confidence": 0.7,
                    "statute_reference": "Hindu Succession Act, 1956 — Section 6",
                    "source_document_ref": f"vendor={vendor.get('entity_name')}",
                })

            if is_trust and not has_trust_deed and not represented_by:
                findings.append({
                    "type": "UNVERIFIED_SIGNATORY_AUTHORITY", "severity": "high",
                    "doc_ids": ["SALE_DEED"],
                    "summary": f"Trust seller '{vendor.get('entity_name')}' without supporting trust deed",
                    "legal_detail": "A Trust can only sell property through its trustees as authorized by the Trust Deed. "
                                    "No Trust Deed or authorizing resolution was found in the bundle.",
                    "suggestion": "Obtain Trust Deed and trustee resolution authorizing the sale.",
                    "confidence": 0.85,
                    "statute_reference": "Indian Trusts Act, 1882 — Section 47",
                    "source_document_ref": f"vendor={vendor.get('entity_name')}",
                })

    return findings


def _check_inheritance_succession(documents: list[dict]) -> list[dict]:
    """B2.3: Inheritance/succession gaps."""
    findings = []
    doc_types_present = {d.get("document_type") for d in documents if d.get("document_type")}
    has_legal_heir = "LEGAL_HEIR_CERTIFICATE" in doc_types_present
    has_will = "WILL" in doc_types_present
    has_court_order = "COURT_ORDER" in doc_types_present
    has_succession_cert = any(
        "succession" in (d.get("document_type") or "").lower() for d in documents
    )

    ec_docs = [d for d in documents if d.get("document_type") == "ENCUMBRANCE_CERTIFICATE"]
    for doc in ec_docs:
        sd = doc.get("structured_json", {}) or {}
        ledger = sd.get("historical_ledger") or sd.get("transactions") or []
        for tx in ledger:
            if not isinstance(tx, dict):
                continue
            tx_type = (tx.get("transaction_type") or "").lower()
            is_inheritance = any(x in tx_type for x in ["inheritance", "inherited", "succession", "death", "deceased", "legal heir"])

            if is_inheritance:
                if not has_legal_heir and not has_will and not has_court_order and not has_succession_cert:
                    findings.append({
                        "type": "MISSING_SUCCESSION_DOCUMENT", "severity": "high",
                        "doc_ids": ["ENCUMBRANCE_CERTIFICATE"],
                        "summary": "EC shows inheritance transfer but no succession document found",
                        "legal_detail": f"The EC ledger shows transaction '{tx.get('transaction_type')}' "
                                        f"on {tx.get('execution_date')} as an inheritance/succession transfer. "
                                        "However, no Legal Heir Certificate, Succession Certificate, Will, or Court Order "
                                        "is present in the bundle to establish the legal basis of this transfer.",
                        "suggestion": "Obtain Succession Certificate, Legal Heir Certificate, or probated Will "
                                      "to verify the inheritance transfer.",
                        "confidence": 0.9,
                        "statute_reference": "Indian Succession Act, 1925 — Sections 370-374",
                        "source_document_ref": f"EC transaction: {tx.get('registration_reference', '')} dated {tx.get('execution_date', '')}",
                    })
                elif has_court_order:
                    findings.append({
                        "type": "MISSING_SUCCESSION_DOCUMENT", "severity": "low",
                        "doc_ids": ["ENCUMBRANCE_CERTIFICATE", "COURT_ORDER"],
                        "summary": "Inheritance transfer with Court Order — verify order scope",
                        "legal_detail": "EC shows inheritance transfer and a Court Order is present. "
                                        "Verify that the Court Order specifically covers the property in question.",
                        "suggestion": "Confirm Court Order relates to this property's succession.",
                        "confidence": 0.7,
                        "statute_reference": "Indian Succession Act, 1925",
                        "source_document_ref": f"EC transaction: {tx.get('registration_reference', '')}",
                    })

    return findings


def _check_valuation_consistency(documents: list[dict]) -> list[dict]:
    """B2.4: Valuation consistency — declared consideration vs guidance value vs market value."""
    findings = []
    declared_consideration = None
    guidance_value = None
    guidance_value_date = None
    market_values = []

    for doc in documents:
        sd = doc.get("structured_json", {}) or {}
        doc_type = doc.get("document_type", "")

        if doc_type == "SALE_DEED":
            fin = sd.get("financial_summary") or {}
            declared_consideration = fin.get("declared_consideration_amount")
            valuation = sd.get("statutory_valuation_endorsement") or {}
            mv = valuation.get("estimated_market_value")
            if mv:
                market_values.append(("SALE_DEED", mv))

        if doc_type in ("PROPERTY_REGISTER_CARD",):
            gv = sd.get("guidance_value") or {}
            guidance_value = gv.get("value")
            guidance_value_date = gv.get("order_date")

        if doc_type == "ENCUMBRANCE_CERTIFICATE":
            ledger = sd.get("historical_ledger") or sd.get("transactions") or []
            for tx in ledger:
                if isinstance(tx, dict):
                    fin = tx.get("financials") or {}
                    mv = fin.get("market_value") or fin.get("consideration_amount")
                    if mv:
                        market_values.append((f"EC tx #{tx.get('transaction_index', '?')}", mv))

    if declared_consideration is not None and guidance_value is not None:
        try:
            dc = float(declared_consideration)
            gv = float(guidance_value)
            ratio = dc / gv if gv > 0 else 0

            if ratio < 0.7:
                findings.append({
                    "type": "UNDERVALUATION", "severity": "high",
                    "doc_ids": ["SALE_DEED", "PROPERTY_REGISTER_CARD"],
                    "summary": f"Consideration (₹{dc:,.0f}) is {ratio*100:.0f}% of guidance value (₹{gv:,.0f})",
                    "legal_detail": f"Declared consideration of ₹{dc:,.0f} is only {ratio*100:.0f}% of the "
                                    f"guidance value of ₹{gv:,.0f}. This significant undervaluation may trigger "
                                    "Section 47A of the Karnataka Stamp Act, 1957 (reference to Deputy Commissioner "
                                    "for undervaluation) and could be a Benami transaction indicator under the "
                                    "Benami Transactions (Prohibition) Act, 1988.",
                    "suggestion": "Verify that proper stamp duty has been paid on the higher of "
                                  "consideration vs. guidance value. Check for Form 1-A communication.",
                    "confidence": 0.9,
                    "statute_reference": "Karnataka Stamp Act, 1957 — Section 47A",
                    "source_document_ref": f"declared_consideration={declared_consideration}, guidance_value={guidance_value}",
                })
            elif ratio > 1.5:
                findings.append({
                    "type": "FINANCIAL_MISMATCH", "severity": "low",
                    "doc_ids": ["SALE_DEED", "PROPERTY_REGISTER_CARD"],
                    "summary": f"Consideration (₹{dc:,.0f}) exceeds guidance value (₹{gv:,.0f}) significantly",
                    "legal_detail": f"Consideration is {ratio:.1f}x the guidance value, which is unusual "
                                    "but may reflect market premium.",
                    "suggestion": "Verify sufficient funds disclosure if required.",
                    "confidence": 0.5,
                    "statute_reference": "Karnataka Stamp Act, 1957",
                    "source_document_ref": f"declared_consideration={declared_consideration}, guidance_value={guidance_value}",
                })

        except (ValueError, TypeError) as e:
            pass

    # Check consideration vs market value in EC
    for source, mv in market_values:
        if declared_consideration is not None and mv is not None:
            try:
                dc = float(declared_consideration)
                emv = float(mv)
                if dc < emv * 0.7:
                    findings.append({
                        "type": "UNDERVALUATION", "severity": "medium",
                        "doc_ids": ["SALE_DEED", "ENCUMBRANCE_CERTIFICATE"],
                        "summary": f"Consideration (₹{dc:,.0f}) vs market value (₹{emv:,.0f}) from {source}",
                        "legal_detail": f"Declared consideration (₹{dc:,.0f}) is significantly lower than "
                                        f"the market value recorded in {source} (₹{emv:,.0f}).",
                        "suggestion": "Verify the reason for the valuation difference.",
                        "confidence": 0.7,
                        "statute_reference": "Karnataka Stamp Act, 1957 — Section 47A",
                        "source_document_ref": f"declared_consideration={declared_consideration}, market_value_from={source}={mv}",
                    })
            except (ValueError, TypeError):
                pass

    return findings


def _check_rera_applicability(documents: list[dict], property_type: str) -> list[dict]:
    """B2.5: RERA applicability check."""
    findings = []
    if property_type not in ("apartment",):
        return findings

    doc_types_present = {d.get("document_type") for d in documents if d.get("document_type")}
    sale_deeds = [d for d in documents if d.get("document_type") == "SALE_DEED"]

    has_project_ref = False
    project_name = None
    for sd_doc in sale_deeds:
        sd = sd_doc.get("structured_json", {}) or {}
        ps = sd.get("property_schedule") or {}
        pn = ps.get("project_name")
        if pn:
            has_project_ref = True
            project_name = pn
            break
        intended_usage = (ps.get("intended_usage") or "").lower()
        if any(x in intended_usage for x in ["apartment", "flat", "building", "project"]):
            has_project_ref = True
            break

    has_builder_agreement = "BUILDER_BUYER_AGREEMENT" in doc_types_present
    has_rera_doc = any(
        "rera" in (d.get("document_type") or "").lower()
        or (d.get("structured_json") or {}).get("rera_registration_number")
        for d in documents
    )

    if has_project_ref and not has_rera_doc:
        findings.append({
            "type": "RERA_REGISTRATION_UNVERIFIED", "severity": "medium",
            "doc_ids": ["SALE_DEED"],
            "summary": f"Property appears to be in a project/development{' (' + str(project_name) + ')' if project_name else ''}",
            "legal_detail": f"The property is described as part of a project{' (' + str(project_name) + ')' if project_name else ''}. "
                            "Under Section 3 of the RERA Act, 2016, projects with >500 sqm or 8+ units must register with RERA. "
                            "RERA registration status CANNOT be confirmed from documents alone — external portal verification is required.",
            "suggestion": "Verify RERA registration at https://rera.karnataka.gov.in. "
                          "If the project is exempt, obtain exemption certificate.",
            "confidence": 1.0,
            "statute_reference": "RERA Act, 2016 — Section 3",
            "source_document_ref": f"apartment_project={'Yes' if has_project_ref else 'No'}, rera_reg_doc_present={has_rera_doc}",
        })

    if has_builder_agreement and not has_rera_doc:
        findings.append({
            "type": "RERA_REGISTRATION_UNVERIFIED", "severity": "high",
            "doc_ids": ["BUILDER_BUYER_AGREEMENT"],
            "summary": "Builder-Buyer Agreement present but RERA registration unverified",
            "legal_detail": "A Builder-Buyer Agreement has been identified. Promoters are required to register "
                            "the project with RERA before entering into such agreements. "
                            "The absence of RERA registration details is a serious compliance gap.",
            "suggestion": "Confirm RERA registration number from the promoter or the Karnataka RERA portal.",
            "confidence": 0.95,
            "statute_reference": "RERA Act, 2016 — Section 3",
            "source_document_ref": "builder_buyer_agreement_present=true",
        })

    return findings


def _check_document_recency(documents: list[dict]) -> list[dict]:
    """B2.6: Document recency — EC search + guidance value within 6-12 months."""
    findings = []
    now = datetime.now()
    six_months_ago = now.timestamp() - (180 * 24 * 3600)
    twelve_months_ago = now.timestamp() - (365 * 24 * 3600)

    for doc in documents:
        sd = doc.get("structured_json", {}) or {}
        doc_type = doc.get("document_type", "")

        # EC recency
        if doc_type == "ENCUMBRANCE_CERTIFICATE":
            fm = sd.get("file_metadata") or {}
            end_date = fm.get("search_end_date")
            if end_date:
                try:
                    ed = datetime.strptime(str(end_date)[:10], "%Y-%m-%d")
                    days_old = (now - ed).days
                    if days_old > 365:
                        findings.append({
                            "type": "DOCUMENT_EXPIRY", "severity": "medium",
                            "doc_ids": ["ENCUMBRANCE_CERTIFICATE"],
                            "summary": f"EC search end date is {days_old} days old ({str(end_date)[:10]})",
                            "legal_detail": f"The EC search period ended on {str(end_date)[:10]}, which is "
                                            f"{days_old} days ago. Encumbrance searches have a practical shelf life "
                                            "of 6-12 months. Transactions after this date are not captured.",
                            "suggestion": "Obtain a fresh EC to capture any transactions after the search end date.",
                            "confidence": 0.9,
                            "statute_reference": "Registration Act, 1908",
                            "source_document_ref": f"search_end_date={end_date}",
                        })
                    elif days_old > 180:
                        findings.append({
                            "type": "DOCUMENT_EXPIRY", "severity": "low",
                            "doc_ids": ["ENCUMBRANCE_CERTIFICATE"],
                            "summary": f"EC search end date is {days_old} days old — consider refreshing",
                            "legal_detail": f"The EC is {days_old} days old. While still usable, "
                                            "a more recent EC (within 6 months) is recommended for closing.",
                            "suggestion": "Consider obtaining an updated EC before transaction closing.",
                            "confidence": 0.8,
                            "statute_reference": "Registration Act, 1908",
                            "source_document_ref": f"search_end_date={end_date}",
                        })
                except (ValueError, TypeError):
                    pass

        # PRC guidance value recency
        if doc_type == "PROPERTY_REGISTER_CARD":
            gv = sd.get("guidance_value") or {}
            gv_date = gv.get("order_date")
            if gv_date:
                try:
                    gd = datetime.strptime(str(gv_date)[:10], "%Y-%m-%d")
                    days_old = (now - gd).days
                    if days_old > 730:
                        findings.append({
                            "type": "GUIDANCE_VALUE_ISSUE", "severity": "medium",
                            "doc_ids": ["PROPERTY_REGISTER_CARD"],
                            "summary": f"Guidance value order date is {days_old} days old ({str(gv_date)[:10]})",
                            "legal_detail": f"The guidance value was last updated on {str(gv_date)[:10]}, which is "
                                            f"{days_old} days old (>2 years). Stale guidance values may not reflect "
                                            "current market rates.",
                            "suggestion": "Verify current guidance value from the sub-registrar's office.",
                            "confidence": 0.7,
                            "statute_reference": "Karnataka Stamp Act, 1957 — Section 45A",
                            "source_document_ref": f"guidance_value_order_date={gv_date}",
                        })
                except (ValueError, TypeError):
                    pass

    return findings


def _check_expected_missing_docs(documents: list[dict], property_type: str) -> list[dict]:
    """B2.7: Expected-but-missing documents given property type."""
    findings = []
    doc_types_present = {d.get("document_type") for d in documents if d.get("document_type")}
    expected = EXPECTED_DOCUMENTS_BY_PROPERTY_TYPE.get(property_type, EXPECTED_DOCUMENTS_BY_PROPERTY_TYPE["house"])

    missing = [d for d in expected if d not in doc_types_present]
    if missing:
        findings.append({
            "type": "MISSING_EXPECTED_DOCUMENT", "severity": "medium",
            "doc_ids": list(doc_types_present),
            "summary": f"Missing documents for {property_type} property: {', '.join(missing)}",
            "legal_detail": f"For a {property_type} property, the following documents are expected in a complete due diligence "
                            f"bundle but were not found: {', '.join(missing)}. See Table 1 of the Karnataka Property "
                            "Due Diligence Reference Guide.",
            "suggestion": f"Obtain the following missing documents: {', '.join(missing)}.",
            "confidence": 1.0,
            "statute_reference": "General due diligence standards",
            "source_document_ref": f"property_type={property_type}, docs_present={','.join(sorted(doc_types_present))}",
        })

    # Always check for critical missing docs
    for critical in ["SALE_DEED", "ENCUMBRANCE_CERTIFICATE"]:
        if critical not in doc_types_present:
            findings.append({
                "type": "MISSING_DOCUMENT", "severity": "high",
                "doc_ids": [critical],
                "summary": f"Missing {critical} — critical for title verification",
                "legal_detail": f"A {critical} is essential for establishing a complete chain of title. "
                                "Without it, title cannot be verified.",
                "suggestion": f"Upload {critical} to enable complete verification.",
                "confidence": 1.0,
                "statute_reference": "Registration Act, 1908",
                "source_document_ref": "bundle_missing",
            })

    return findings


# ── Existing methods ──────────────────────────────────────────────────────


def _ensure_legal_opinion_format(report_text: str, verdict: str,
                                   risk_result: dict, findings: list[dict]) -> str:
    """Ensure final_report follows the legal opinion format (B6)."""
    # If report already has the structured sections, return as-is
    if "EXECUTIVE SUMMARY" in report_text and "VERDICT & RISK SCORE" in report_text:
        return report_text

    critical = [f for f in findings if f.get("severity") in ("critical", "high")]
    other = [f for f in findings if f.get("severity") in ("medium", "low")]

    lines = []
    lines.append("EXECUTIVE SUMMARY")
    lines.append(f"Verification of {len(findings)} finding(s) across the case bundle. ")
    lines.append(f"The overall verdict is {verdict}. {risk_result.get('verdict_reason', '')}")
    lines.append("")

    lines.append("VERDICT & RISK SCORE")
    lines.append(f"Verdict: {verdict}")
    lines.append(f"Risk Score: {risk_result.get('risk_score', 'N/A')} / {risk_result.get('max_possible_score', 'N/A')}")
    lines.append(f"Risk Level: {risk_result.get('verdict', 'N/A')}")
    lines.append(f"Normalized Risk: {risk_result.get('normalized_risk_pct', 'N/A')}%")
    lines.append("")

    lines.append("CRITICAL ISSUES (High Severity)")
    if critical:
        for f in critical:
            statute = f.get("statute_reference", "")
            doc_ref = f.get("source_document_ref", "")
            lines.append(f"- {f.get('type', '')}: {f.get('summary', '')}")
            if statute:
                lines.append(f"  Statute: {statute}")
            if doc_ref:
                lines.append(f"  Source: {doc_ref}")
            lines.append(f"  {f.get('legal_detail', '')}")
            lines.append(f"  Suggestion: {f.get('suggestion', '')}")
            lines.append("")
    else:
        lines.append("No critical issues found.")
        lines.append("")

    lines.append("OTHER FINDINGS")
    if other:
        for f in other:
            lines.append(f"- [{f.get('severity', 'N/A').upper()}] {f.get('type', '')}: {f.get('summary', '')}")
            lines.append(f"  {f.get('legal_detail', '')}")
            lines.append("")
    else:
        lines.append("No other findings.")
        lines.append("")

    lines.append("MISSING DOCUMENTS")
    missing = [f for f in findings if f.get("type") in ("MISSING_DOCUMENT", "MISSING_EXPECTED_DOCUMENT")]
    if missing:
        for f in missing:
            lines.append(f"- {f.get('summary', '')}")
    else:
        lines.append("No missing documents identified.")
    lines.append("")

    lines.append("RECOMMENDED NEXT STEPS")
    for f in findings[:5]:
        lines.append(f"- {f.get('suggestion', '')}")
    lines.append("")

    lines.append("DISCLAIMER")
    lines.append("This report is generated by an AI-assisted verification system and is not a substitute "
                  "for an independent legal opinion from a qualified advocate. All findings should be "
                  "independently verified by a human legal professional before any action is taken.")

    return "\n".join(lines)


def _compact_fields(sd: dict) -> dict:
    """Extract only the fields that matter for cross-document checks from structured data."""
    compact = {}

    if isinstance(sd, dict):
        fm = sd.get("file_metadata") or sd.get("document_metadata") or {}
        compact["registration_number"] = fm.get("registration_number")
        compact["execution_date"] = fm.get("execution_date")
        compact["registration_date"] = fm.get("registration_date")
        compact["issuing_office"] = fm.get("issuing_office")

        ps = sd.get("property_schedule") or sd.get("property_identification") or {}
        compact["survey_number"] = ps.get("survey_number") or ps.get("city_survey_number")
        compact["cts_number"] = ps.get("cts_number")
        compact["pid"] = sd.get("consumer_details", {}).get("pid") if isinstance(sd.get("consumer_details"), dict) else None

        sc = sd.get("search_criteria") or {}
        compact["search_start_date"] = sc.get("search_start_date") or fm.get("search_start_date")
        compact["search_end_date"] = sc.get("search_end_date") or fm.get("search_end_date")

        fin = sd.get("financial_summary") or {}
        compact["consideration"] = fin.get("declared_consideration_amount")
        compact["stamp_duty"] = fin.get("stamp_duty_paid_amount") or fin.get("stamp_duty_amount")

        parties = sd.get("parties") or {}
        vendors = parties.get("vendors") or []
        purchasers = parties.get("purchasers") or []
        compact["vendor_names"] = [v.get("entity_name") for v in vendors if isinstance(v, dict)]
        compact["purchaser_names"] = [p.get("entity_name") for p in purchasers if isinstance(p, dict)]

        ledger = sd.get("historical_ledger") or sd.get("transactions") or []
        if ledger:
            compact["historical_ledger"] = []
            for tx in ledger:
                if not isinstance(tx, dict):
                    continue
                parties = tx.get("parties") or {}
                vendors = parties.get("vendors") or []
                purchasers = parties.get("purchasers") or []
                prop = tx.get("property_details") or {}
                fin = tx.get("financials") or {}
                compact["historical_ledger"].append({
                    "tx_index": tx.get("transaction_index"),
                    "execution_date": tx.get("execution_date"),
                    "doc_reference": tx.get("registration_reference"),
                    "type": tx.get("transaction_type"),
                    "consideration": fin.get("consideration_amount"),
                    "vendors": vendors,
                    "purchasers": purchasers,
                    "survey_no": prop.get("survey_no") or prop.get("survey_number") or prop.get("plot_no"),
                    "cts_no": prop.get("cts_no") or prop.get("cts_number") or prop.get("pid_no"),
                    "description": prop.get("description"),
                })

        holders = sd.get("holders") or []
        if holders:
            compact["holder_names"] = [h.get("name") for h in holders if isinstance(h, dict)]

        gv = sd.get("guidance_value") or {}
        if gv:
            compact["guidance_value"] = gv.get("value")
            compact["guidance_value_order_date"] = gv.get("order_date")

    return compact


def _fallback_verification(documents: list[dict],
                            deterministic_findings: list[dict] | None = None) -> dict:
    """Simple deterministic fallback when LLM is unavailable."""
    findings = list(deterministic_findings or [])
    doc_types = {doc.get("document_type"): doc for doc in documents if doc.get("document_type")}

    critical = ["SALE_DEED", "ENCUMBRANCE_CERTIFICATE"]
    for c in critical:
        if c not in doc_types:
            findings.append({
                "type": "MISSING_DOCUMENT", "severity": "high",
                "doc_ids": [c], "summary": f"Missing {c} — critical for title verification",
                "legal_detail": "A complete title due diligence requires both a deed and EC.",
                "suggestion": f"Upload {c} to enable complete verification.", "confidence": 1.0,
            })

    risk_result = compute_risk_score(findings)
    verdict = risk_result["verdict"]

    report = _ensure_legal_opinion_format(
        f"Cross-doc verification run in fallback mode (Groq API unavailable). "
        f"Reviewed {len(documents)} documents via deterministic checks only.",
        verdict, risk_result, findings,
    )

    return {
        "verdict": verdict,
        "risk_score": risk_result["risk_score"],
        "risk_score_details": risk_result,
        "findings": findings,
        "final_report": report,
        "_analytics": {"model": "fallback", "input_tokens": 0, "output_tokens": 0, "latency_ms": 0, "cost_usd": 0},
    }
