"""Central constants for document types and pipeline statuses.

Extracted verbatim from `backend/constants.py`.
"""

# ── Document types ──────────────────────────────────────────────────────────

SALE_DEED = "SALE_DEED"
GIFT_DEED = "GIFT_DEED"
ENCUMBRANCE_CERTIFICATE = "ENCUMBRANCE_CERTIFICATE"
RTC_PAHANI = "RTC_PAHANI"
KHATA = "KHATA"
MUTATION = "MUTATION"
PROPERTY_REGISTER_CARD = "PROPERTY_REGISTER_CARD"
PROPERTY_TAX_ASSESSMENT = "PROPERTY_TAX_ASSESSMENT"
E_PAYMENT_RECEIPT = "E_PAYMENT_RECEIPT"
TAX_RECEIPT = "TAX_RECEIPT"
LEGAL_HEIR_CERTIFICATE = "LEGAL_HEIR_CERTIFICATE"
PARTITION_DEED = "PARTITION_DEED"
COURT_ORDER = "COURT_ORDER"
POSSESSION_CERTIFICATE = "POSSESSION_CERTIFICATE"
CONVERSION_ORDER = "CONVERSION_ORDER"
CDP_PLAN = "CDP_PLAN"
RERA_CERTIFICATE = "RERA_CERTIFICATE"
LITIGATION_AFFIDAVIT = "LITIGATION_AFFIDAVIT"
ALLOTMENT_LETTER = "ALLOTMENT_LETTER"
BUILDING_LICENSE = "BUILDING_LICENSE"
COMPLETION_CERTIFICATE = "COMPLETION_CERTIFICATE"
UNKNOWN_DOC = "UNKNOWN"

# ── Pipeline statuses ───────────────────────────────────────────────────────

STATUS_PROCESSING = "processing"
STATUS_PREPROCESSED = "preprocessed"
STATUS_OCR_DONE = "ocr_done"
STATUS_MERGED = "merged"
STATUS_CLASSIFYING = "classifying"
STATUS_CLASSIFICATION_FAILED = "classification_failed"
STATUS_STRUCTURING = "structuring"
STATUS_STRUCTURED = "structured"
STATUS_FAILED = "failed"
STATUS_NO_TRANSACTIONS = "no_transactions"
STATUS_PENDING_RETRY = "pending_retry"
